# Generated by Django 4.2.6 on 2023-10-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_login', '0002_tempuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempuser',
            name='username',
        ),
    ]
